### ISSUE TITLE
No me permite instalar el boton_mercadopago 

### ISSUE THREAD

**Issue by nahe-consulting-group** [ctmil/boton_mercadopago#5]
odoo 13 localización moldeo en ubuntu 18.04 
agrego el modulo a addons path y al hacer click en instalar salta el siguiente error: 
Cabe aclarar que SI instale con el virtualenv pip3 install -r requirements.txt
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1331, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1319, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo13/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo13/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/odoo13/odoo/odoo/modules/module.py", line 376, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo13/odoo/repositorios/moldeo-boton-mercadopago/boton_mercadopago/__init__.py", line 1, in <module>
    from . import models
  File "/opt/odoo13/odoo/repositorios/moldeo-boton-mercadopago/boton_mercadopago/models/__init__.py", line 1, in <module>
    from . import odoo_mercadopago
  File "/opt/odoo13/odoo/repositorios/moldeo-boton-mercadopago/boton_mercadopago/models/odoo_mercadopago.py", line 2, in <module>
    from mercadopago import mercadopago
ImportError: cannot import name 'mercadopago'

**Comment by nahe-consulting-group** [comment]
Requirement already satisfied: mercadopago in /opt/odoo13/odoo-venv/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: requests in /opt/odoo13/odoo-venv/lib/python3.6/site-packages (from mercadopago->-r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /opt/odoo13/odoo-venv/lib/python3.6/site-packages (from requests->mercadopago->-r requirements.txt (line 1)) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/odoo13/odoo-venv/lib/python3.6/site-packages (from requests->mercadopago->-r requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: idna<2.9,>=2.5 in /opt/odoo13/odoo-venv/lib/python3.6/site-packages (from requests->mercadopago->-r requirements.txt (line 1)) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/odoo13/odoo-venv/lib/python3.6/site-packages (from requests->mercadopago->-r requirements.txt (line 1)) (3.0.4)

**Comment by nahe-consulting-group** [comment]
se resolvió instalando pip3 install mercadopago == 1.*  el modulo version 2 no anda con este botón
