### ISSUE TITLE
No puede importar modulo mercadopago en V13

### ISSUE THREAD

**Issue by trixocom** [ctmil/boton_mercadopago#6]
Se instala pip3 install mercadopago
Se intenta instalar el modulo y da el siguiente error:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 464, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 574, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 428, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 404, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/mnt/extra-addons/varios/boton_mercadopago/__init__.py", line 1, in <module>
    from . import models
  File "/mnt/extra-addons/varios/boton_mercadopago/models/__init__.py", line 1, in <module>
    from . import odoo_mercadopago
  File "/mnt/extra-addons/varios/boton_mercadopago/models/odoo_mercadopago.py", line 2, in <module>
    from mercadopago import mercadopago
ImportError: cannot import name 'mercadopago' from 'mercadopago' (c)

*El archivo que hace referencia /var/lib/odoo/.local/lib/python3.7/site-packages/ esta presente en el sistema.

**Comment by csrocha** [comment]
Hola @trixocom , primero comprueba que el pip que ejecutaste corresponda al mismo entorno donde funciona odoo.

**Comment by trixocom-dev** [comment]
Es un docker con imagen mantenido por Alitux Fabrega, probe de ejecutar desde consola del contenedor, luego como root con docker exec -u 0. pero tampoco funciono. Entiendo que el entorno es uno solo en este caso.

**Comment by csrocha** [comment]
No es la mejor opción para instalar un paquete entrar dentro de la instancia, porque cuando reinicias odoo se reinicia con la imagen original. Deberías tomar el Dockerfile con el que construiste esa imagen, o crear uno nuevo a partir de esa imagen, y agregar el pip install ahí adentro.
